[package]
name = "hot_reload"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hot_reload"
path = "src/main.rs"

[dependencies]
sword = { workspace = true, features = ["hot-reload"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
