[application]
graceful-shutdown = false
name = "SocketIO Adapter Example"
host = "0.0.0.0"
port = 8081
request-timeout = { enabled = true, timeout = "15s", display = true }
body-limit = { max-size = "5MB", display = true }

[socketio-server]
enabled = true
parser = "common"
transports = ["websocket", "polling"]
