[application]
name = "SocketIO Adapter Example"
host = "0.0.0.0"
port = 8081
graceful-shutdown = false

[application.request-timeout]
enabled = true
timeout = "15s"
display = true

[application.body-limit]
max-size = "5MB"
display = true

[socketio]
enabled = true
parser = "common"
transports = ["websocket", "polling"]

[tracing]
enabled = true
default-filter = "info,sword=info"
format = "pretty"
time-style = "none"
with-fields = []
