[application]
host = "0.0.0.0"
port = 8080

[my-custom-section]
custom_key = "custom_value"

[cors]
allowed_http_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_http_headers = ["Content-Type", "Authorization"]