[application]
host = "0.0.0.0"
port = 8080
body_limit = "10MB"
allowed_mime_types = [
    "image/png", 
    "application/pdf", 
]

[my-custom-section]
custom_key = "custom_value"
env_var = "${USER:default_value}"

[cors]
allowed_http_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_http_headers = ["Content-Type", "Authorization"]