[application]
name = "gRPC Greeter"
host = "0.0.0.0"
port = 50051
graceful-shutdown = true
enable-tonic-reflection = true

[application.body-limit]
max-decoding-message-size = "2 MiB"
max-encoding-message-size = "2 MiB"
display = true

[tracing]
enabled = true
display = false
filter = "info,sword=info"
format = "dev"
time-style = "none"
time-pattern = "%H:%M:%S"
with-fields = []

[cors]
display = false
