[package]
name = "tower-middlewares"
version = "0.1.0"
edition = "2021"

[dependencies]
sword = { workspace = true }
serde = { workspace = true }
tower-http = { workspace = true }

[features]
default = []
multipart = []
shaku-di = []
hot-reload = []
cookies = []
helmet = []