[application]
host = "0.0.0.0"
port = 8080
body_limit = "10MB"
request_timeout_secs = 30

[cors]
allowed_http_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_http_headers = ["Content-Type", "Authorization"]
