[package]
name = "config-file"
version = "0.1.0"
edition = "2021"

[dependencies]
sword = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
multipart = []
shaku-di = []
hot-reload = []
cookies = []
helmet = []