[application]
graceful-shutdown = false
name = "Interceptors Example"
host = "0.0.0.0"
port = 8081
body-limit = { max-size = "2MB", display = true }
request-timeout = { enabled = true, timeout = "15s", display = true }

[socketio]
enabled = true
parser = "common"
transports = ["websocket", "polling"]

[tracing]
enabled = true
timer = false
target = false
