[application]
graceful-shutdown = false
name = "Interceptors Example"

[server]
host = "0.0.0.0"
port = 8081
body-limit = { max-size = "2MB", display = true }
request-timeout = { enabled = true, timeout = "15s", display = true }

[socketio-server]
enabled = true
parser = "common"
transport = ["websocket", "polling"]
