[application]
graceful-shutdown = false
name = "Interceptors Example"
host = "0.0.0.0"
port = 8081

[application.request-timeout]
enabled = true
timeout = "15s"
display = true

[application.body-limit]
max-size = "5MB"
display = true

[socketio]
enabled = true
parser = "common"
transports = ["websocket", "polling"]

[cors]
allow-origins = ["*"]
allow-methods = ["GET", "POST", "PUT", "DELETE"]

[tracing]
enabled = true
default-filter = "info,sword=info"
format = "dev"
time-style = "local"
time-pattern = "%H:%M:%S"
with-fields = []
