[package]
name = "helmet"
version = "0.1.0"
edition = "2024"

[dependencies]
sword = { workspace = true, features = ["helmet"] }

[features]
default = []
multipart = []
shaku-di = []
hot-reload = []
cookies = []
helmet = []