[package]
name = "graceful-shutdown"
version = "0.1.0"
edition = "2021"

[dependencies]
sword = { workspace = true }
tokio = { workspace = true }

[features]
default = []
multipart = []
shaku-di = []
hot-reload = []
cookies = []
helmet = []