[package]
name = "dependency-injection"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "di"
path = "src/main.rs"

[dependencies]
sword = { workspace = true }
serde = { workspace = true }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio"] }
dotenv = "0.15.0"
